version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: Man&kingdom1
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432
